name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      # 获取代码
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: install dependencies
      run: npm install -g pnpm && pnpm install

    - name: build
      run: pnpm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: ".env, /node_modules/, ecosystem.config.js"
          SCRIPT_AFTER: |
            whoami
            ls -al
            pwd
            echo "devlink-server restart"
            /home/ubuntu/.nvm/versions/node/v16.20.0/bin/pm2 /home/ubuntu/app/devlink/devlink-server/restart ecosystem.config.js

